apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ include "vllm-coldstart-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm-coldstart-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vllm-coldstart-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
